sudo: false
cache: packages
language: r

r_github_packages: r-lib/remotes#340

r_packages:
  - covr

env:
  matrix:
  - _R_CHECK_SYSTEM_CLOCK_=0
  global:
    secure: c2sfOu8pVctQkP7KP0jDbHLWrM3TDwrefMixrW7he3ZUgQJl2+FNcMyb0ry/wgMdVGoFtDlVB/JGb0A3L07VnbQ3514mnS6VvogsdfAkmpV5avbd8pbmnFrWqOMCzdwur/yODEGcDDrt5oG6+pZccAgBi1//+8MaQ1oYMmf41zNzPSVBENUwHzrJdzQ7Zo0Vb7sJJSo5s5Cwwur1+111pRPRVJbLjz7lVyZWjRdUcpkkNN48/IYrhXqBXQgqQ68su+QzHVI+hSG6k6UTN+3QC1X9i5rygzXduALIejh+B+81iSk0bi0A/HDR4p7ibS4SJ2IXVfjcz8EPp2N66SvIlLywHi6OSDsxVhnldsxKKdrmNxBfs28e8RhhKnXeWwxFExS9l+IkK4CuBAjCpLIgkdbwqaB2GraF5TxmtHv949fi8+LxmyipkLF/+wUd9z0mkgXSwbv4YxTXIGf6txLyZhkdHjvXnC0kEpRFXuByNWeAG9tpnoAnbFR3nd0HKe08CwDZLe4ZFSHo6vAjIHXREei4W+bzj89ypFjZGK+mcfwgdnwC5mxfQIiExfUahpGC5VZv24hFaKcw1j0VjgJKbHbnewSjRZ3hTA44sU9pG4DouN7mPnf/V3uFG3SAOota0Hdkpl3twbmlKmh4G8uoMq354FwIakISTbT+U7X6xGM=

matrix:
  include:
  - r: devel
    after_success:
      - Rscript -e 'library(covr); codecov()'
  - r: release
    os: osx
    osx_image: xcode10.1
    before_install:
    - sudo tlmgr install inconsolata
    - sw_vers
  - r: release
  - r: oldrel
  - r: 3.5

before_install:
- echo "TRAVIS_OS_NAME = $TRAVIS_OS_NAME"

addons:
  apt:
    packages:
    - ghostscript
    - graphviz
    - libjq-dev
    - libv8-dev
  homebrew:
    packages:
    - ghostscript
    - graphviz
    - jq
    - v8

# after_success:
#   - test $TRAVIS_PULL_REQUEST == "false" &&
#     test $TRAVIS_BRANCH == "master" &&
#     bash deploy.sh
